import { Event } from "../types/event";

export const events: Event[] = [
  {
    id: "1",
    title: "Elegant Wedding Venue",
    category: "Wedding",
    description: "Beautiful wedding venue with stunning decor and professional services. Perfect for your dream wedding with capacity for up to 300 guests. Includes ceremony and reception spaces.",
    venue: "Grand Ballroom",
    location: "Downtown Plaza, New York",
    date: "2026-04-15",
    time: "14:00",
    price: 5000,
    capacity: 300,
    booked: 0,
    image: "https://images.unsplash.com/photo-1767986012138-4893f40932d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVnYW50JTIwd2VkZGluZyUyMGNlcmVtb255fGVufDF8fHx8MTc3MzU5NjYzNXww&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["Catering", "Decoration", "Photography", "Parking", "Audio System"],
    duration: "8 hours"
  },
  {
    id: "2",
    title: "Corporate Conference Hall",
    category: "Conference",
    description: "State-of-the-art conference facility equipped with modern technology. Ideal for business meetings, seminars, and corporate events with professional support.",
    venue: "Tech Convention Center",
    location: "Business District, San Francisco",
    date: "2026-04-22",
    time: "09:00",
    price: 2500,
    capacity: 200,
    booked: 45,
    image: "https://images.unsplash.com/photo-1571645163064-77faa9676a46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3Jwb3JhdGUlMjBjb25mZXJlbmNlJTIwZXZlbnR8ZW58MXx8fHwxNzczNjk3MzIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["WiFi", "Projector", "Microphones", "Coffee Service", "Parking"],
    duration: "Full day"
  },
  {
    id: "3",
    title: "Birthday Party Celebration",
    category: "Birthday",
    description: "Fun and vibrant party space perfect for birthday celebrations. Customizable themes and entertainment options available for all ages.",
    venue: "Party Paradise",
    location: "Lakeside Avenue, Chicago",
    date: "2026-05-10",
    time: "16:00",
    price: 800,
    capacity: 50,
    booked: 12,
    image: "https://images.unsplash.com/photo-1650584997985-e713a869ee77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiaXJ0aGRheSUyMHBhcnR5JTIwY2VsZWJyYXRpb258ZW58MXx8fHwxNzczNjc2OTM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["Decoration", "Entertainment", "Catering", "Cake Service", "Party Favors"],
    duration: "4 hours"
  },
  {
    id: "4",
    title: "Outdoor Music Festival",
    category: "Concert",
    description: "Open-air venue perfect for concerts and music festivals. Premium sound system and lighting equipment included. Great outdoor atmosphere.",
    venue: "Sunset Amphitheater",
    location: "Riverside Park, Austin",
    date: "2026-06-20",
    time: "18:00",
    price: 8000,
    capacity: 500,
    booked: 280,
    image: "https://images.unsplash.com/photo-1573463908761-567b9356c64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdXRkb29yJTIwY29uY2VydCUyMGZlc3RpdmFsfGVufDF8fHx8MTc3MzY1ODM0MHww&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["Sound System", "Stage", "Lighting", "Security", "Food Vendors"],
    duration: "6 hours"
  },
  {
    id: "5",
    title: "Graduation Ceremony Venue",
    category: "Graduation",
    description: "Prestigious venue for graduation ceremonies with elegant ambiance. Professional photography and video services available.",
    venue: "University Auditorium",
    location: "Campus Drive, Boston",
    date: "2026-05-25",
    time: "10:00",
    price: 3000,
    capacity: 400,
    booked: 350,
    image: "https://images.unsplash.com/photo-1686213011371-2aff28a08f16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwZ3JhZHVhdGlvbiUyMHN0dWRlbnRzfGVufDF8fHx8MTc3MzY2Mzk5N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["Seating", "Stage", "Audio Visual", "Photography", "Parking"],
    duration: "3 hours"
  },
  {
    id: "6",
    title: "Business Meeting Room",
    category: "Meeting",
    description: "Professional meeting space for small to medium business gatherings. Equipped with all modern amenities for productive meetings.",
    venue: "Executive Suites",
    location: "Corporate Tower, Seattle",
    date: "2026-04-18",
    time: "13:00",
    price: 500,
    capacity: 30,
    booked: 8,
    image: "https://images.unsplash.com/photo-1765768737206-8f94009da6f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMG1lZXRpbmclMjB2ZW51ZXxlbnwxfHx8fDE3NzM2MjU1MDd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    amenities: ["WiFi", "Whiteboard", "Coffee", "Projector", "Video Conferencing"],
    duration: "2 hours"
  }
];